<?php
/**
 * Created by PhpStorm.
 * User: khaled
 * Date: 3/4/16
 * Time: 10:29 AM
 */

$us_states = array(
    'AL'=>'ALABAMA',
    'AK'=>'ALASKA',
    'AS'=>'AMERICAN SAMOA',
    'AZ'=>'ARIZONA',
    'AR'=>'ARKANSAS',
    'CA'=>'CALIFORNIA',
    'CO'=>'COLORADO',
    'CT'=>'CONNECTICUT',
    'DA'=>'DEMOCRATS ABROAD',
    'DE'=>'DELAWARE',
    'DC'=>'DISTRICT OF COLUMBIA',
    'FM'=>'FEDERATED STATES OF MICRONESIA',
    'FL'=>'FLORIDA',
    'GA'=>'GEORGIA',
    'GU'=>'GUAM GU',
    'HI'=>'HAWAII',
    'ID'=>'IDAHO',
    'IL'=>'ILLINOIS',
    'IN'=>'INDIANA',
    'IA'=>'IOWA',
    'KS'=>'KANSAS',
    'KY'=>'KENTUCKY',
    'LA'=>'LOUISIANA',
    'ME'=>'MAINE',
    'MH'=>'MARSHALL ISLANDS',
    'MD'=>'MARYLAND',
    'MA'=>'MASSACHUSETTS',
    'MI'=>'MICHIGAN',
    'MN'=>'MINNESOTA',
    'MS'=>'MISSISSIPPI',
    'MO'=>'MISSOURI',
    'MT'=>'MONTANA',
    'NE'=>'NEBRASKA',
    'NV'=>'NEVADA',
    'NH'=>'NEW HAMPSHIRE',
    'NJ'=>'NEW JERSEY',
    'NM'=>'NEW MEXICO',
    'NY'=>'NEW YORK',
    'NC'=>'NORTH CAROLINA',
    'ND'=>'NORTH DAKOTA',
    'MP'=>'NORTHERN MARIANA ISLANDS',
    'OH'=>'OHIO',
    'OK'=>'OKLAHOMA',
    'OR'=>'OREGON',
    'PW'=>'PALAU',
    'PA'=>'PENNSYLVANIA',
    'PR'=>'PUERTO RICO',
    'RI'=>'RHODE ISLAND',
    'SC'=>'SOUTH CAROLINA',
    'SD'=>'SOUTH DAKOTA',
    'TN'=>'TENNESSEE',
    'TX'=>'TEXAS',
    'UT'=>'UTAH',
    'VT'=>'VERMONT',
    'VI'=>'VIRGIN ISLANDS',
    'VA'=>'VIRGINIA',
    'WA'=>'WASHINGTON',
    'WV'=>'WEST VIRGINIA',
    'WI'=>'WISCONSIN',
    'WY'=>'WYOMING'
);
$caucusinfo = array(
    array("short"=>"AL", "fullname"=>"Alabama", "electtype"=>"Primary", "eventwhen"=>"3-1-16"),
    array("short"=>"AR", "fullname"=>"Arkansas", "electtype"=>"Primary", "eventwhen"=>"3-1-16"),
    array("short"=>"CO", "fullname"=>"Colorado", "electtype"=>"Caucus", "eventwhen"=>"3-1-16"),
    array("short"=>"GA", "fullname"=>"Georgia", "electtype"=>"Primary", "eventwhen"=>"3-1-16"),
    array("short"=>"MA", "fullname"=>"Massachusetts", "electtype"=>"Primary", "eventwhen"=>"3-1-16"),
    array("short"=>"MN", "fullname"=>"Minnesota", "electtype"=>"Caucus", "eventwhen"=>"3-1-16"),
    array("short"=>"OK", "fullname"=>"Oklahoma", "electtype"=>"Primary", "eventwhen"=>"3-1-16"),
    array("short"=>"TN", "fullname"=>"Tenessee", "electtype"=>"Primary", "eventwhen"=>"3-1-16"),
    array("short"=>"TX", "fullname"=>"Texas", "electtype"=>"Primary", "eventwhen"=>"3-1-16"),
    array("short"=>"VT", "fullname"=>"Vermont", "electtype"=>"Primary", "eventwhen"=>"3-1-16"),
    array("short"=>"VA", "fullname"=>"Virgina", "electtype"=>"Primary", "eventwhen"=>"3-1-16"),
    array("short"=>"KS", "fullname"=>"Kansas", "electtype"=>"Caucus", "eventwhen"=>"3-5-16 8:00:00"),
    array("short"=>"LA", "fullname"=>"Louisiana", "electtype"=>"Primary", "eventwhen"=>"3-5-16 8:00:00"),
    array("short"=>"NE", "fullname"=>"Nebraska", "electtype"=>"Caucus", "eventwhen"=>"3-5-16 7:00:00"),
    array("short"=>"MN", "fullname"=>"Maine", "electtype"=>"Caucus", "eventwhen"=>"3-6-16 7:00:00"),
    array("short"=>"MI", "fullname"=>"Michigan", "electtype"=>"Primary", "eventwhen"=>"3-8-16"),
    array("short"=>"MS", "fullname"=>"Mississippi", "electtype"=>"Primary", "eventwhen"=>"3-8-16"),
    array("short"=>"IL", "fullname"=>"Illinois", "electtype"=>"Primary", "eventwhen"=>"3-15-16"),
    array("short"=>"FL", "fullname"=>"Florida", "electtype"=>"Primary", "eventwhen"=>"3-15-16"),
    array("short"=>"OH", "fullname"=>"Maine", "electtype"=>"Primary", "eventwhen"=>"3-15-16"),
    array("short"=>"NC", "fullname"=>"North Carolina", "electtype"=>"Primary", "eventwhen"=>"3-15-16"),
    array("short"=>"AZ", "fullname"=>"Arizona", "electtype"=>"Primary", "eventwhen"=>"3-22-16"),
    array("short"=>"UT", "fullname"=>"Utah", "electtype"=>"Caucus", "eventwhen"=>"3-22-16"),
    array("short"=>"ID", "fullname"=>"Idaho", "electtype"=>"Caucus", "eventwhen"=>"3-22-16"),
    array("short"=>"WA", "fullname"=>"Washington", "electtype"=>"Caucus", "eventwhen"=>"3-26-16"),
    array("short"=>"HI", "fullname"=>"Hawaii", "electtype"=>"Caucus", "eventwhen"=>"3-26-16"),
    array("short"=>"AK", "fullname"=>"Alaska", "electtype"=>"Caucus", "eventwhen"=>"3-26-16"),
    array("short"=>"WI", "fullname"=>"Wisconsin", "electtype"=>"Primary", "eventwhen"=>"4-5-16"),
    array("short"=>"WY", "fullname"=>"Wyoming", "electtype"=>"Caucus", "eventwhen"=>"4-9-16"),
    array("short"=>"NY", "fullname"=>"New York", "electtype"=>"Primary", "eventwhen"=>"4-19-16"),
    array("short"=>"PA", "fullname"=>"Pennsylvania", "electtype"=>"Primary", "eventwhen"=>"4-26-16"),
    array("short"=>"CT", "fullname"=>"Connecticut", "electtype"=>"Primary", "eventwhen"=>"4-26-16"),
    array("short"=>"MD", "fullname"=>"Maryland", "electtype"=>"Primary", "eventwhen"=>"4-26-16"),
    array("short"=>"RI", "fullname"=>"Rhode Island", "electtype"=>"Primary", "eventwhen"=>"4-26-16"),
    array("short"=>"DE", "fullname"=>"Delaware", "electtype"=>"Primary", "eventwhen"=>"4-26-16"),
    array("short"=>"IN", "fullname"=>"Indiana", "electtype"=>"Primary", "eventwhen"=>"5-3-16"),
    array("short"=>"WV", "fullname"=>"West Virginia", "electtype"=>"Primary", "eventwhen"=>"5-10-16"),
    array("short"=>"OR", "fullname"=>"Oregon", "electtype"=>"Primary", "eventwhen"=>"5-17-16"),
    array("short"=>"KY", "fullname"=>"Kentucky", "electtype"=>"Primary", "eventwhen"=>"5-17-16"),
    array("short"=>"PR", "fullname"=>"Puerto Rico", "electtype"=>"Primary", "eventwhen"=>"6-5-16"),
    array("short"=>"CA", "fullname"=>"California", "electtype"=>"Primary", "eventwhen"=>"6-7-16"),
    array("short"=>"NJ", "fullname"=>"New Jersy", "electtype"=>"Primary", "eventwhen"=>"6-7-16"),
    array("short"=>"NM", "fullname"=>"New Mexico", "electtype"=>"Primary", "eventwhen"=>"6-7-16"),
    array("short"=>"MT", "fullname"=>"Montana", "electtype"=>"Primary", "eventwhen"=>"6-7-16"),
    array("short"=>"ND", "fullname"=>"North Dakota", "electtype"=>"Primary", "eventwhen"=>"6-7-16"),
    array("short"=>"SD", "fullname"=>"South Dakota", "electtype"=>"Primary", "eventwhen"=>"6-7-16"),
    array("short"=>"DC", "fullname"=>"District of Columbia", "electtype"=>"Primary", "eventwhen"=>"6-14-16")
);
